stages:
  data_split:
    cmd: python src/data_split.py
    deps:
    - data/all_data/
    - src/data_split.py
    params:
    - base
    - data_split
    outs:
    - data/test
    - data/train
  train:
    cmd: python src/train.py
    deps:
    - data/train/
    - src/train.py
    - src/unet.py
    params:
    - base
    - train
    outs:
    - models/output-model.keras
    - results/train/
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/test/
    - models/output-model.keras
    - src/evaluate.py
    - src/unet.py
    params:
    - base
    - evaluate
    outs:
    - results/evaluate/
artifacts:
  output-model:
    path: models/output-model.keras
    type: model
    desc: Model trained to segment (insert sample type).
    labels:
    - cv
    - segmentation
metrics:
- results/train/metrics.json
- results/evaluate/metrics.json
plots:
- results/train/plots/metrics:
    x: step
- results/evaluate/plots/images
