base:
  random_seed: 0
  model_image_size: 256
  # Loss needs to be here since both train and evaluate need it
  loss_function: dice_loss # Options: binary_crossentropy, iou_loss, dice_loss
  image_channels: 1
  output_classes: 1
data_split:
  test_split: 0.2
  data_dir: data/all_data/
  train_data_dir: data/train/
  test_data_dir: data/test/
train:
  train_data_dir: data/train/
  model_save_dir: models/
  batch_size: 6
  epochs: 20
  conv_activation_function: relu # Options: relu, sigmoid
  final_activation_function: sigmoid # Options: softmax (for multi-class), sigmoid (for binary)
  learning_rate: 1e-03
  augment_zoom_percent: 0.1
  augment_flip_rotate: true
  norm_upper_bound: 4
  norm_lower_bound: -1
  validation_split: 0.2
evaluate:
  model_path: models/output-model.keras
  test_data_dir: data/test/



